[package]
name = "test_internal"
description = "Provides bindings for the C library"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[build-dependencies]
cc = "1.2"

[dependencies]
crex = { path = "../.." }

[features]
export = [ ]
variadic = [ ]
